language: java

jdk: oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

install:
  - chmod +x .travis_install.sh
  - ./.travis_install.sh

script:
  - chmod +x .travis_build.sh
  - ./.travis_build.sh

after_succes:
  - ./gradlew publishPlugin